///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class AppAuthUpgradeInfoValue {
/*
{
  "upgrade": false,
  "download": "https://www.baidu.com/app/download",
  "dialog": "本次升级，主要解决了up生活不能自理的问题"
} 
*/

  bool upgrade;
  String download;
  String dialog;

  AppAuthUpgradeInfoValue({
    this.upgrade,
    this.download,
    this.dialog,
  });
  AppAuthUpgradeInfoValue.fromJson(Map<String, dynamic> json) {
    upgrade = json["upgrade"];
    download = json["download"]?.toString();
    dialog = json["dialog"]?.toString();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["upgrade"] = upgrade;
    data["download"] = download;
    data["dialog"] = dialog;
    return data;
  }
}

class AppAuthUpgradeInfo {
/*
{
  "code": 200,
  "text": "操作成功！",
  "value": {
    "upgrade": false,
    "download": "https://www.baidu.com/app/download",
    "dialog": "本次升级，主要解决了up生活不能自理的问题"
  }
} 
*/

  int code;
  String text;
  AppAuthUpgradeInfoValue value;

  AppAuthUpgradeInfo({
    this.code,
    this.text,
    this.value,
  });
  AppAuthUpgradeInfo.fromJson(Map<String, dynamic> json) {
    code = json["code"]?.toInt();
    text = json["text"]?.toString();
    value = json["value"] != null
        ? AppAuthUpgradeInfoValue.fromJson(json["value"])
        : null;
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["code"] = code;
    data["text"] = text;
    if (value != null) {
      data["value"] = value.toJson();
    }
    return data;
  }
}

///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class AppInitNoticeConValue {
/*
{
  "switch": true,
  "notice": "欢迎来到xxx电影app"
} 
*/

  bool theSwitch;
  String notice;

  AppInitNoticeConValue({
    this.theSwitch,
    this.notice,
  });
  AppInitNoticeConValue.fromJson(Map<String, dynamic> json) {
    theSwitch = json["switch"];
    notice = json["notice"]?.toString();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["switch"] = theSwitch;
    data["notice"] = notice;
    return data;
  }
}

class AppInitNoticeCon {
/*
{
  "code": 200,
  "text": "操作成功！",
  "value": {
    "switch": true,
    "notice": "欢迎来到xxx电影app"
  }
} 
*/

  int code;
  String text;
  AppInitNoticeConValue value;

  AppInitNoticeCon({
    this.code,
    this.text,
    this.value,
  });
  AppInitNoticeCon.fromJson(Map<String, dynamic> json) {
    code = json["code"]?.toInt();
    text = json["text"]?.toString();
    value = json["value"] != null
        ? AppInitNoticeConValue.fromJson(json["value"])
        : null;
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["code"] = code;
    data["text"] = text;
    if (value != null) {
      data["value"] = value.toJson();
    }
    return data;
  }
}
