///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class TypeListSchemaValue {
/*
{
  "_id": "0",
  "name": "首页",
  "active": true,
  "link": "/"
} 
*/

  String Id;
  String name;
  bool active;
  String link;

  TypeListSchemaValue({
    this.Id,
    this.name,
    this.active,
    this.link,
  });
  TypeListSchemaValue.fromJson(Map<String, dynamic> json) {
    Id = json["_id"]?.toString();
    name = json["name"]?.toString();
    active = json["active"];
    link = json["link"]?.toString();
  }
}

class TypeListSchema {
/*
{
  "code": 200,
  "text": "操作成功！",
  "value": [
    {
      "_id": "0",
      "name": "首页",
      "active": true,
      "link": "/"
    }
  ]
} 
*/

  int code;
  String text;
  List<TypeListSchemaValue> value;

  TypeListSchema({
    this.code,
    this.text,
    this.value,
  });
  TypeListSchema.fromJson(Map<String, dynamic> json) {
    code = json["code"]?.toInt();
    text = json["text"]?.toString();
    if (json["value"] != null) {
      var v = json["value"];
      var arr0 = List<TypeListSchemaValue>();
      v.forEach((v) {
        arr0.add(TypeListSchemaValue.fromJson(v));
      });
      value = arr0;
    }
  }
}
